### ISSUE TITLE
Keeps saying sentence count is zero...

### ISSUE THREAD

**Issue by joshash** [shivam5992/textstat#11]
My code is the following:

```
from textstat.textstat import textstat
if __name__ == '__main__':
	test_data = "This is a sentence. I would like to analyze it. I want to know its stats."

	print(textstat.flesch_reading_ease(test_data))
	print(textstat.smog_index(test_data))
	print(textstat.automated_readability_index(test_data))
	print(textstat.dale_chall_readability_score(test_data))
	print(textstat.difficult_words(test_data))
	print(textstat.linsear_write_formula(test_data))
	print(textstat.gunning_fog(test_data))
	print(textstat.text_standard(test_data))
```

And I keep getting this error:
```
Traceback (most recent call last):
  File "/Users/ashkij/Documents/Programming/Python Stuff/Preten.py", line 1, in <module>
    from textstat.textstat import textstat
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/textstat/textstat.py", line 82
    print "Error(ASL): Sentence Count is Zero, Cannot Divide"
                                                            ^
SyntaxError: invalid syntax
```

**Comment by stuboo** [comment]
This custom exception is replacing the normal error you would encounter in python 3.5:
`SyntaxError: Missing parentheses in call to 'print'`

To fix it, open textstat.py and put parenthesis around all of the print statements.

So, on line 85 you'll change `print "Error(ASL): Sentence Count is Zero, Cannot Divide"` to `print("Error(ASL): Sentence Count is Zero, Cannot Divide")`

More info: [http://stackoverflow.com/questions/25445439/what-does-syntaxerror-missing-parentheses-in-call-to-print-mean-in-python](url)
